### ISSUE TITLE
cannot access zzbfm

### ISSUE THREAD

**Issue by mattx1992** [pusheco/pushe-android-studio-sample#27]
با سلام و عرض ادب.
من یه فروشگاه اینترنتی دارم که برای تکمیل فرم و دلیور محصولات از مپ  گوگل داخل برنامه استفاده می کنم.
وقتی 
implementation 'com.pushpole.android:pushsdk:1.7.0'
رو داخل 
build.gradle 
میگذارم و می خوام اجرا بگیرم
error: cannot access zzbfm
class file for com.google.android.gms.internal.zzbfm not found
رو روی تمام کلاس های مپ مثل 
CameraPosition
میده. لطفا راهنمایی بفرمایید مشکل چیه. با تشکر.

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

شما باید به این ریپو گزارش مشکل بدید

</div>

https://github.com/push-pole/android-studio-sample
