### ISSUE TITLE
Could not find core.jar (androidx.core:core)

### ISSUE THREAD

**Issue by HarryAshlein** [pusheco/pushe-android-studio-sample#28]
سلام من بعد از ادد کردن کتابخونه پوشه به پروژه طبق توضیحات توی سایت وقیتی میخوام که پروژه رو بیلد بگیرم به این ارور میخورم:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find core.jar (androidx.core:core:1.2.0).

باید چیکار کنم؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

خطایی که دارید توی این بخش خلاصه میشه:

</div>

```
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
Could not find core.jar (androidx.core:core:1.2.0).
```
<div dir='rtl'>

فکر می‌کنم این مورد ار سمت گریدل باشه. چون اگر گذرازتحریم درست کار کنه نباید توی دریافت لایبرری مشکلی پیش بیاد. این موارد رو بررسی کنید:

* ۱- ابزار گذر از تحریم داشته باشید، برای مثال شکن یا ...
* ۲- کش گریدل رو از آدرس زیر پاک کنید و دوباره سینک کنید

</div>

**Windows:**: `C:\Users\<your_name>\.gradle\caches`

**Linux**: `~/.gradle/caches`

<div dir='rtl'>

* ۳- توی فایل `gradle.properties` این دو خط وجود داشته باشن:

</div>

```
android.enableJetifier=true
android.useAndroidX=true
```
