### ISSUE TITLE
Failed to resolve: play-services-ads-identifier

### ISSUE THREAD

**Issue by negroAk** [pusheco/pushe-android-studio-sample#31]
سلام
در نسخه های قبلی این مشکل وجود نداشت اما در نسخه co.pushe.plus:base:2.0.5 پس از build با خطای "Failed to resolve: play-services-ads-identifier" مواجه میشم. لطفا راهنمایی کنید.
ممنون

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
کلا خطاهای Failed to resolve X بخاطر این پیش میاد که یا لایبرری وجود نداره و یا لایبرری وجود داره اما خطایی رخ داده که گریدل نتونسته اون لایبرری رو کش کنه.

نسخه‌های قبلی از FirebaseCore برای ایمپورت کد AdvertisingId استفاده می‌کردن و با منسوخ شدن اون لایبرری اون رو حذف کردیم و جاش این لایبرری اومد.

با توجه به اینکه این لایبرری وجود داره (توی سرور گوگل هست) پس دلیل خطا میتونه invalid بودن کش گریدل باشه.

می‌تونید این موارد رو تست کنید:

1- ابتدا Clean project کنید
2- از منوی فایل Invalidate cache and restart رو بزنید
3- با فعال‌بودن ابزار گذراز تحریم دوباره تست کنید
4- در صورتی که مشکل کماکان وجود داشت از آدرس C/Users/userName/.gradle یا ~/.gradle فولدر Cache رو پاک کنید و مجددا اندروید استودیو رو باز کنید و دیوایس رو سینک کنید.

</div>

**Comment by negroAk** [comment]
با پاک کردن فولدر cache حل شد ممنون.
