### ISSUE TITLE
Duplicate classes when adding RxJava

### ISSUE THREAD

**Issue by ajaxpersian** [pusheco/pushe-android-studio-sample#33]
```
Duplicate class io.reactivex.BackpressureStrategy found in modules
 jetified-rxjava-2.0.5.jar (co.pushe.plus:rxjava:2.0.5) and
 jetified-rxjava-2.0.6.jar (io.reactivex.rxjava2:rxjava:2.0.6)
```

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام توی این لینک توضیحات کامل در این مورد داده شده:
</div>

[Pushe advance set up for Android studio](http://docs.pushe.co/docs/android-studio/advanced-setup#%D8%A7%D8%B6%D8%A7%D9%81%D9%87%DA%A9%D8%B1%D8%AF%D9%86-rxjava)
