### ISSUE TITLE
Please set your project ID  دریافت ارور 

### ISSUE THREAD

**Issue by morteza-developer** [pusheco/pushe-android-studio-sample#34]
[error.txt](https://github.com/pusheco/pushe-android-studio-sample/files/4637830/error.txt)
سلام

این ارور رو در در لاگ کت دریافت می کنم 
Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.

که ارور رو هم در فایل ضمیمه کردم 
لطفا راهنمایی کنید

**Comment by fsghasemi** [comment]
سلام
از com.google.firebase:firebase-messaging در پروژتون استفاده کردید؟ و اگر آره چه نسخه ای است؟

**Comment by morteza-developer** [comment]
com.google.firebase:firebase-messaging:20.1.0

**Comment by morteza-developer** [comment]
مشکل همون ورژن  
firebase-messaging 
بود که  باید حتما ورژن 20.1.0 باشه
و کتابخانه های زیر هم نباید در پروژه باشه

implementation 'com.google.firebase:firebase-iid:20.1.0'
 implementation 'com.google.firebase:firebase-analytics:17.4.1'

**Comment by fsghasemi** [comment]
اپتون چه ساختاری داره که علاوه بر پوشه از firebase-messaging هم استفاده میکنین؟

**Comment by morteza-developer** [comment]
من اول که پروژه رو با فایربیس کاکنت کردم 
firebase-messaging
 در پروژم بود و خب نمی دونستم که سرویس پوشه نیاز نداره حتی 
firebase-messaging 
در پژوه باشه که خداروشکر مشکل حل شد
خیلی سپاسگزارم

**Comment by fsghasemi** [comment]
عالی. بله سرویس پوشه نیازی نداره که کتابخونه
 firebase-messaging
 در اپ وجود داشته باشه.
