### ISSUE TITLE
خطای کانفلیکت با کتابخانه  work-runtime-ktx

### ISSUE THREAD

**Issue by RezaMasoudi** [pusheco/pushe-android-studio-sample#35]
نمیتونم پوشه رو در کنار کتابخانه 
`androidx.work:work-runtime-ktx:2.3.4`
نصب کنم چنین خطایی به وجود میاد
`Duplicate class androidx.work.ArrayCreatingInputMerger found in modules classes.jar (android.arch.work:work-runtime:1.0.1) and classes.jar (androidx.work:work-runtime:2.3.4)
`
به این صورت اضافه کرده ام
` implementation "androidx.work:work-runtime-ktx:2.3.4"
 implementation 'co.pushe.plus:base:2.1.1'`

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
تشکر بابت اینکه مشکلتون رو با ما در میون گذاشتید.

پوشه توی نسخه‌ی 2.1.0 به بعد از AndroidX استفاده میکنه و یکی از اون لایبرری‌های تحت تاثیر WorkManager هست.

نسخه‌ی WorkManager استفاده شده در پوشه (نسخه‌ی 2.1.1) نسخه‌ی 2.3.4 هست.
خطایی که شما دارید:

```
Duplicate class androidx.work.ArrayCreatingInputMerger found in modules classes.jar (android.arch.work:work-runtime:1.0.1) and classes.jar (androidx.work:work-runtime:2.3.4)
```

میگه که این دو تا لایبرری با هم تداخل دارن:  
* `android.arch.work:work-runtime:1.0.1`
* `androidx.work:work-runtime:2.3.4`

با توجه به اینکه پوشه از لایبرری اول استفاده نمیکنه و شما هم همینطور. پس دلیل باید لایبرری دیگه‌ای باشه.

پیشنهاد می‌کنم از تسک **Dependencies** در گریدلتون استفاده کنید و از اونجا ببینید کدوم لایبرری اون رو اضافه کرده.

توی عکس زیر می‌تونید ببینید تسکش رو:  

![image](https://user-images.githubusercontent.com/21319971/83431898-54c73580-a44d-11ea-9035-04b0a7fa2e30.png)

بعد اجراش توی خروجی به دنبال `android.arch.workmanager` بگردید. در صورتی که پیدا شد و از زیرمجموعه‌ی پوشه بود لطفا تصویر ساختار درختی‌ای که نشون میده چجوری به پوشه میرسه رو توی همین‌جا برای بنده ارسال کنید تا بررسی کنم.

با تشکر.

</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
از نسخه‌ی **2.1.0** این مشکل به لطف مهاجرت لایبرری به AndroidX رفع شده.

[**Release note**](https://docs.pushe.co/docs/android-studio/releasenote#%D9%86%D8%B3%D8%AE%D9%87-%DB%B2%DB%B1%DB%B0)

</div>
