### ISSUE TITLE
❓ [ERROR]: Could not find fragment-1.2.4.jar

### ISSUE THREAD

**Issue by Arzed21** [pusheco/pushe-android-studio-sample#36]
Could not find fragment-1.2.4.jar (androidx.fragment:fragment:1.2.4).
Searched in the following locations:
    https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.2.4/fragment-1.2.4.jar

**Comment by mahdi-malv** [comment]
<div dir='rtl'>
سلام

- اگر پروژه از AndroidX استفاده نمیکنه لطفا یا مایگریتش کنید یا از نسخه‌های قبل از ۲.۱.۰ استفاده کنید.
- در صورتی که همه چیز به طور کامل در وضعیت درستی‌ هستند ممکنه کش گریدل به مشکل خورده باشه

توی #28 میتونید راه‌حل حالت دوم رو بررسی کنید
</div>

**Comment by mahdi-malv** [comment]
#28

**Comment by Arzed21** [comment]
ممنون بابت پاسخگویی
در هنگام مایگریت این هشدار رو میده:No Usages Found in the Project

سعی کردم که از ورژن 2.0.5 استفاده کنم ولی  ارور:Could not find play-services-ads-identifier-16.0.0.jar (com.google.android.gms:play-services-ads-identifier:16.0.0)رو میده

کش گریدل رو هم پاک کردم ولی حل نشد

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

@Arzed21 مشکل حل شد؟
ممنون میشم توضیح بدید که دلیلش چی بود.

</div>

**Comment by Danial-Barazandeh** [comment]
من هم این مشکل رو دارم و موارد گرفته شده رو تست کردم اما همچنان همین ارور رو میگیرم

**Comment by Arzed21** [comment]
> من هم این مشکل رو دارم و موارد گرفته شده رو تست کردم اما همچنان همین ارور رو میگیرم

مشکل من بعد از اضافه کردن چند لایبراری حل شد،(androidx.fragment:fragment:1.2.4)
اول همین لایبراری رو اد کردم بعد از این 2 بار دیگه ارور نبود 2 لایبراری دیگه رو داد بعد از اد کردن اونا مشکلم حل شد
