### ISSUE TITLE
دریافت device_id

### ISSUE THREAD

**Issue by MrCrazy1376** [pusheco/pushe-android-studio-sample#37]
سلام
چگونه می توان device_id را دریافت نمود؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

نسخه‌ی نهایی پوشه:

</div>

```java
Pushe.getDeviceId();
```
<div dir='rtl'>

و نسخه‌های قبلتر:

</div>

```java
Pushe.getAndroidId();
```
<div dir='rtl'>

با احترام.

</div>
