### ISSUE TITLE
Program type already present: android.support.v4.app.INotificationSideChannel$Stub

### ISSUE THREAD

**Issue by alirezadh65** [pusheco/pushe-android-studio-sample#38]

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
بنظر مشکل از AndroidX هست.
اگر نسخه ی نهایی پوشه رو استفاده کنید باید پروژه از AndroidX استفاده کنه.

[**Release note**](https://docs.pushe.co/docs/android-studio/releasenote)

</div>
