### ISSUE TITLE
خطا   class file for com.google.android.gms.internal.zzbgl not found

### ISSUE THREAD

**Issue by shmasoomilarei** [pusheco/pushe-android-studio-sample#39]
سلام
در اپلیکیشن من از کتابخانه  
play-services:12.0.1
استفاده شده واز مکانیابی گوگل مپ، وپس از اضافه کردن کتابخانه پوشه خطای زیر دیده می شود
error: cannot access zzbgl markerOptions.position(latLng)
class file for com.google.android.gms.internal.zzbgl not found
لطفا راهنمایی بفرمایید

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
پوشه از لایبرری‌های لوکیشن و ads استفاده میکنه.
چون نسخه‌ی این لایبرری‌ها همیشه جزو آخرین نسخه‌ها هستن ممکنه مشکل بخاطر تداخل نسخه‌ی مختلف لایبرری‌ها و ایجاد ناسازگاری بینشون (لایبرری‌های گوگل و فایربیس) پیش بیاد.

احتمال داره ارتقا همه‌ی نسخه‌ها به اخرین نسخه مشکل رو حل کنه.

</div>
