### ISSUE TITLE
خطا در initialize

### ISSUE THREAD

**Issue by MohammadBarati** [pusheco/pushe-android-studio-sample#41]
سلام خسته نباشید این خطا پیش میاد 

` E/PushPole: Exception in readAndInitHandlers() 
    java.lang.ClassNotFoundException: co.ronash.pushe.internal.log.handlers.SentryHandler`

`  Caused by: java.lang.ClassNotFoundException: Didn't find class "co.ronash.pushe.internal.log.handlers.SentryHandler" on path: $$$$$$$$$`

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
تگ `E/PushPole:` مربوط به پوش‌پل هست.
لطفا مورد رو توی گیتهاب پوش پل مطرح کنید یا به ساپورت پوش پل اطلاع بدید:

</div>

[**Push-pole Github page**](https://github.com/push-pole)
