### ISSUE TITLE
غیرفعال کردن گزارش خطا پوشه و استفاده از کرش لایتیکس فایربیس

### ISSUE THREAD

**Issue by homayoun-a** [pusheco/pushe-android-studio-sample#45]
سلام. وقت بخیر. چطور میشود گزارش خطای پوشه (لاگ های Exception Caught) را غیرفعال کرد که با فایربیس تداخل پیدا نکنه؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام.
ExceptionCatcher پوشه صرفا خطاهایی که توشون استک تریس پوشه باشه و مربوط به خود کتابخونه باشه Catch می‌کنه و به DefaultExceptionCatcher نمی‌ده تا باعث بسته شدن اپ نشن.
اما در صورتی که خطا متعلق به پوشه نباشه به DefaultCatcher پاس داده میشه و هر Catcher دیگه‌ای میتونه اون رو بگیره.

منظورتون از تداخل رو متوجه نشدم. استفاده از چندتا Catcher مشکل ایجاد نمیکنه. شما می‌خواید خطاهای داخلی کتابخونه رو هم داشته باشید؟

</div>

**Comment by mahdi-malv** [comment]
درود
من این ایشو رو میندم
در صورتی که در مورد مشکلی کماکان وجود داشت لطفا ایشو رو مجددا باز کنید
