### ISSUE TITLE
مشکل اضافه کردن ماژول hms

### ISSUE THREAD

**Issue by mr-sarsarabi** [pusheco/pushe-android-studio-sample#47]
سلام وقتی این ماژول رو به پروژه اضافه میکنم  هنگام سینک گریدل این اررور رو میده

co.pushe.plus:hms:2.4.1

با استفاده از وی پی ان هم رفع نمیشه

    Execution failed for task ':app:checkDebugAarMetadata'.
    > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
       > Could not find com.huawei.hms:push:5.0.2.300.
         Searched in the following locations:
           - https://dl.google.com/dl/android/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
           - https://repo.maven.apache.org/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
           - https://jcenter.bintray.com/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
           - https://jitpack.io/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
           - https://dl.bintray.com/tapsellorg/maven/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
         Required by:
             project :app > co.pushe.plus:hms:2.4.1
       > Could not find com.huawei.hms:ads-identifier:3.4.29.301.
         Searched in the following locations:
           - https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
           - https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
           - https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
           - https://jitpack.io/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
           - https://dl.bintray.com/tapsellorg/maven/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
         Required by:
             project :app > co.pushe.plus:hms:2.4.1
    
    Possible solution:
     - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
به نظر ریموت هواوی که لایبرری‌هاشو توش قرار میده رو توی repositories اضافه نکردید.

</div>

```
allprojects {
    repositories {
        // Needed for Huawei libraries
        maven {url 'https://developer.huawei.com/repo/'}
        // ...
    }
}
```

[Reference](https://docs.pushe.co/docs/android/hms/intro#%D8%A7%D9%81%D8%B2%D9%88%D8%AF%D9%86-%D9%85%D8%A7%DA%98%D9%88%D9%84)

**Comment by mr-sarsarabi** [comment]
<div dir="rtl">
بله ظاهرا همین بوده مشکل ممنون از شما.
</div>
