### ISSUE TITLE
"exported" attribute for Pushe component while targeting Android 12

### ISSUE THREAD

**Issue by Arsenic1379** [pusheco/pushe-android-studio-sample#49]
![Screenshot from 2021-08-23 09-43-47](https://user-images.githubusercontent.com/89344103/130458043-624285a9-e033-4ed6-a932-44f64433fb46.png)

**Comment by mahdi-malv** [comment]
Hmm

Thanks for reporting this.

Will take a look as soon as I could.
It seems a new release is required.

**Comment by razaghimahdi** [comment]
any solution?

**Comment by BaseMax** [comment]
When a project is a business or shared service.
More support is needed.
A few months have passed since the issue, several requests are open.
This is not a good thing for a business.

Best,
- M.

**Comment by mahdi-malv** [comment]
Sorry for the delay.

I'm currently working on the next release which also includes a fix for this issue where `<service>` tags are required to explicitly define `exported` attr.

First snapshot is up and accessible via

```
maven { url("https://s01.oss.sonatype.org/content/repositories/snapshots/") }
```

with version=`2.6.0-alpha01-SNAPSHOT`

---

It's currently in progress of being tested and rest of the needed features being added to it. I will resolve this issue as soon as `2.6.0` becomes released as stable version.
