### ISSUE TITLE
Problem in sending Notification from Web API

### ISSUE THREAD

**Issue by greenreptile** [pusheco/pushe-android-studio-sample#52]
Hi again

I have a tiny problem in using web api. When I want to send a Json notification via below URL:
[https://api.pushe.co/v2/messaging/notifications/web](url)

api says that :
`شما اجازه محتوای سفارسی اعلان برای انجام این درخواست را ندارید
`

But simple notification is ok. Is it a **permission issue** or configuration ?
(I'm currently in 2weeks free period)

**Comment by mahdi-malv** [comment]
Since this is tool old
Also related to web notification and not android (according to the URL).

Please re-open with extra info if the issue still exists
