### ISSUE TITLE
> Could not find com.huawei.hms:push:5.0.2.300.

### ISSUE THREAD

**Issue by razaghimahdi** [pusheco/pushe-android-studio-sample#54]
Why i get this???
whats the problem?
how to solve that?

FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.huawei.hms:push:5.0.2.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:ads-identifier:3.4.29.301.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:location:5.0.4.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.huawei.hms:push:5.0.2.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:ads-identifier:3.4.29.301.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:location:5.0.4.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.huawei.hms:push:5.0.2.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:ads-identifier:3.4.29.301.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:location:5.0.4.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.huawei.hms:push:5.0.2.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:ads-identifier:3.4.29.301.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:location:5.0.4.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.huawei.hms:push:5.0.2.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:ads-identifier:3.4.29.301.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:location:5.0.4.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.huawei.hms:push:5.0.2.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:ads-identifier:3.4.29.301.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:location:5.0.4.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.huawei.hms:push:5.0.2.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:ads-identifier:3.4.29.301.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:location:5.0.4.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

8: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.huawei.hms:push:5.0.2.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/push/5.0.2.300/push-5.0.2.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:ads-identifier:3.4.29.301.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
       - https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.29.301/ads-identifier-3.4.29.301.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0
   > Could not find com.huawei.hms:location:5.0.4.300.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://repo.maven.apache.org/maven2/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
       - https://jcenter.bintray.com/com/huawei/hms/location/5.0.4.300/location-5.0.4.300.pom
     Required by:
         project :app > co.pushe.plus:hms:2.5.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

**Comment by mahdi-malv** [comment]
Hey

Have you added huawei's maven repos?

In code: https://github.com/pusheco/pushe-android-studio-sample/blob/fdcaf632574872087ed1a30fe311daaf062afe56/build.gradle#L28

**Comment by razaghimahdi** [comment]
yeah actually I did
here is my code:
```gradle
import dependencies.*


// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" } 
         maven { url 'https://developer.huawei.com/repo/' }
        maven { url 'https://dl.bintray.com/tapsellorg/maven' }

    }
    dependencies {

        classpath Build.androidBuildTools
        classpath Build.kotlinGradlePlugin
        classpath Build.hiltAndroid
        classpath Build.navigationSafeArgsGradlePlugin

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by mahdi-malv** [comment]
Well, that's not where they should be. These are for `classpath` plugins and not libraries.

If using latest ones the `repositories -> allProjects` is in `settings.gradle` file maybe. Wherever it is, it's not where you mentioned.

Please re-open the issue if the error wasn't resolved with the fix I suggested.

TIP: Also remove `dl.bintray.com/*`. Those servers are shutdown and not accessible. Libraries (such as Tapsell) are mostly moved to `mavenCentral()` which is added but default.

**Comment by razaghimahdi** [comment]
it worked tnx :)
