### ISSUE TITLE
uses-sdk:minSdkVersion 17 cannot be smaller than version 19 declared in library 

### ISSUE THREAD

**Issue by razaghimahdi** [pusheco/pushe-android-studio-sample#55]
when I try to set minSdk 17, I get this :

Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 19 declared in library [com.google.firebase:firebase-messaging:23.0.0] C:\Users\Administrator\.gradle\caches\transforms-3\0f44e74e3d31e0264edc748bf90abdbe\transformed\jetified-firebase-messaging-23.0.0\AndroidManifest.xml as the library might be using APIs not available in 17
	Suggestion: use a compatible library with a minSdk of at most 17,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.google.firebase.messaging" to force usage (may lead to runtime failures)

but in ur sample u easily made minSdk 17, but I need to make it 19.
why?

**Comment by mahdi-malv** [comment]
Hi

Well, this is mainly related to `fcm-messaging` lib. In the sample you'll see that an earlier version is used [- address](https://github.com/pusheco/pushe-android-studio-sample/blob/fdcaf632574872087ed1a30fe311daaf062afe56/app/build.gradle#L52), but you're forcing it to use `23.0.0` which apparently requires minSDK=19. Pushe itself requires 17 to be the least supported.

Suggestion: Use an earlier version of `firebase-messaging`
