### ISSUE TITLE
onNotificationClick doesn't work

### ISSUE THREAD

**Issue by razaghimahdi** [pusheco/pushe-android-studio-sample#58]
so after adding Pushe Notification while testing I notice if User close the app(even force close) then after getting notification and clicking notification , onNotificationClick  won't work. why is that? any idea?
phone was Xiaomi-Redmi note8

UPDATE: I miss something to say, actually  The onNotificationClick   works **BUT** there is no customContent to getting from it, my notification has JSON all the time , if  app being open and notification come I will get Json **but when** app being close(like force close), I will get notification but there **wont** be any customContent to get

**Comment by razaghimahdi** [comment]
I believe handling battery optimize feature in Xiaomi didn't handle in Pushe very well, any idea?

**Comment by mahdi-malv** [comment]
Hi

Well not really related to either Battery Optimization nor SDK. The reason behind this is that Pushe uses firebase data message to send payloads to the device.

But if you force close the app, it will not be able to receive data payload and thus leading to the message being ignored (or delayed until launch).

In that case neither callbacks are called at all.

However, you're saying you get the notification callback, but no custom-content. That's a bit odd to me.  
Can you say where you are adding you `NotificationCallback`? In Activities or The application file?
Also if you're using APIs please send a digested type of your request body.

**Comment by razaghimahdi** [comment]
I added PusheNotificationListener in mainactivity, and for better testing inside onNotification and onNotificationClick added Toast message , while app is on screen I get Toast message of  custom-content but when app closed then no toast message able to show, so what should i  do to handle it?

**Comment by mahdi-malv** [comment]
The reason behind is pretty straight forward. The listener will only be registered when `MainActivity#onCreate` was called.

When not, listeners are not registered to Pushe so no callbacks will be called.

Suggestion: Add the listeners in `Application#onCreate` instead of activity. Create a custom application class and add it to manifest. Then implement the listeners there.


```kotlin
class MyApplication : android.app.Application() {
   override fun onCreate() {
      super.onCreate()
      // listeners here 
  }
}
```
