### ISSUE TITLE
Execution failed for task ':app:processDebugMainManifest'.

### ISSUE THREAD

**Issue by foray00227** [pusheco/pushe-android-studio-sample#62]
I use the last 32 for compiling the project but it gives a low error, of course I do not want to use version 30 for compiling.

> Manifest merger failed : android:exported needs to be explicitly specified for <service>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by mahdi-malv** [comment]
Use the latest stable version
