### ISSUE TITLE
خطای Manifest merger failed with multiple errors

### ISSUE THREAD

**Issue by mahramane** [pusheco/pushe-android-studio-sample#63]
سلام من خواستم پوشه رو به پروژه اضافه کنم خطای زیر رو میده

compileSdk 31
targetSdk 31

`Merging Errors: Error: android:exported needs to be explicitly specified for element <service#co.pushe.plus.fcm.FcmService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. Aino.app main manifest (this file), line 12`

`Error: android:exported needs to be explicitly specified for element <receiver#co.pushe.plus.receivers.BootCompletedIntentReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. Aino.app main manifest (this file), line 18`

`Error: android:exported needs to be explicitly specified for element <receiver#co.pushe.plus.datalytics.receivers.AppChangeReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. Aino.app main manifest (this file), line 11`

`Error: android:exported needs to be explicitly specified for element <receiver#co.pushe.plus.datalytics.geofence.GpsLocationReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. Aino.app main manifest (this file), line 20`

**Comment by mahramane** [comment]
از ورژن 2.5.0 استفاده میکردم به 2.6.0 تغییر دادم اوکی شد لطفا ورژن رو توی آموزش های پوشه بروز کنید.

**Comment by mahdi-malv** [comment]
سلام
عذرخواهی میکنم بابت تاخیر
ورژن ۲.۶.۱ رو استفاده کنید که موارد دیگه‌ای مثل #61 هم مرتفع بشه
