### ISSUE TITLE
تغییر SmallIcon ناتیفیکیشن

### ISSUE THREAD

**Issue by mahramane** [pusheco/pushe-android-studio-sample#64]
سلام
آیا امکان تغییر SmallIcon برای ناتیفیکیشن های پوشه وجود دارد؟

**Comment by mahdi-malv** [comment]
سلام
عذرخواهی بابت تاخیر
بله ممکن هست. در بخش API باید کلید `notif_icon_url` رو عوض کنید که هم لینک میگیره و هم resource_name (برای resource کلید `notif_icon` رو استفاده کنید

```js
...
"notif_icon_url": "https://notif_icon",
"notif_icon":"resource_name"
...
```
