### ISSUE TITLE
Intent action could not be resolved

### ISSUE THREAD

**Issue by ektefa** [pusheco/pushe-android-studio-sample#65]
Open app page on market not working when clicking on notification.

Environement:
Test Device **LG G8s Android 11**
Market **Cafebazaar**
PusheVersion **2.5.1**

Ensured that package name is set correctly.

> I/Pushe: Notification successfully created, showing notification to user
I/Pushe: Executing Url Action
W/Pushe: Intent action could not be resolved
I/Pushe: Sending notification clicked event to server

**Comment by mahdi-malv** [comment]
2.5.1 is a little old
I expect 2.6.3 to be different. But don't remember if market action was resolved or not. I know some actions are fixed (e.g. URL or WebView)

Please give `2.6.3` a shot
