### ISSUE TITLE
Android version S+ Compatibility issue

### ISSUE THREAD

**Issue by rezafaraji93** [pusheco/pushe-android-studio-sample#67]
E/Pushe: java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by mahdi-malv** [comment]
What version are you using? Is it 2.6.1?

**Comment by rezafaraji93** [comment]
Yes, 2.6.1

**Comment by rezafaraji93** [comment]
And it also happens on 2.6.0

**Comment by rezafaraji93** [comment]
Our application is not working on Android 12 devices, would you please fix this issue ASAP?

**Comment by mahdi-malv** [comment]
Really sorry for the delay. AFAIK, 2.6.1 fixes all PendingIntent related issues. Can you find out what part of the code causes this? For instance the stacktrace (full) can give me some info about this, so share it

**Comment by rezafaraji93** [comment]
It seems 2.6.2 has solved the problem. Thank you.

**Comment by mahdi-malv** [comment]
Awesome
