### ISSUE TITLE
Version 2.6.2: Open URL action doesn't work on Android 11

### ISSUE THREAD

**Issue by alirezaTaheri** [pusheco/pushe-android-studio-sample#68]
Hello,
Opening webpage on click with action `"U"` on Android 11 doesn't work. (It works on Android 7)
I do it with a python script with the following action:
```
        'action':{
            'action_type':'U',
            'url':'https://google.com'
        }
```
Pushe log when receiving the notification and clicking on it:
```
I/Pushe: Notification successfully created, showing notification to user
I/Pushe: Executing Url Action
W/Pushe: Intent action could not be resolved
I/Pushe: Sending notification clicked event to server
I/Pushe: Delivering notification click event to notification listener
```
After clicking on the notification, it gets dismissed and nothing else happens.

**Comment by mahdi-malv** [comment]
Hi
Thanks. I confirm this bug on my side as well. Its bugFix task is in the sprint and will be shipped along with next release.

**Comment by alirezaTaheri** [comment]
Thank you, no this doesn't happen on older Android versions (tested on API level 24 aka Android 7.0 and it works fine).

**Comment by mahdi-malv** [comment]
Allright. I'll update the issue after first preview publish. Stay tuned.

**Comment by mahdi-malv** [comment]
While waiting for the fix, please try this:
- Add this into the manifest:

```xml
<queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
    </queries>
```

[REF](https://developer.android.com/training/package-visibility/use-cases)

**Comment by mahdi-malv** [comment]
I expect `2.6.3` to fix this (adds manifest content in notification module by default)

Please give it a shot

**Comment by alirezaTaheri** [comment]
Thank you, 2.6.3 fixed the problem.
