### ISSUE TITLE
استفاده ی همزمان از پوشه و فایربیس

### ISSUE THREAD

**Issue by sareban101** [pusheco/pushe-android-studio-sample#72]
سلام 
منظور استفاده ی هم زمان از پوشه و فایربیس یعنی فقط سرویس فایربیس شخصی سازی شده رو به پروژه اضافه کنیم و با وب سرویس پوشه جیسون بفرستیم؟
یا
یک اپلیکیشن جدید داخل پنل فایربیس بسازیم و فایل جیسون رو داخل پروژه قرار بدیم و از طریق وب سرویس فایربیس جیسون بفرستیم؟

کدوم یک از این حالت هاست؟
ممنون میشم راهنمایی کنید

**Comment by mahdi-malv** [comment]
سلام
در اصلی دومی. اگر توی پروژه یه اپ باشه با FirebaseMessaging.getInstance()  میشه باهاش ارتباط گرفت. اما پوشه چک میکنه اگر آلردی یه FirebaseMessaging وجود داشت با FirebaseApp دیگه‌ای یه instance میسازه و از اون برای انتقال اطلاعات استفاده میکنه

چون ورودی مسیج‌ها یه service هست برای استفاده همزمان باید کد مورد نیاز پوشه توی سرویس اصلی هم call بشه که پوشه مسیج‌های خودش رو از فایربیس دریافت کنه
