### ISSUE TITLE
Minification with R8 issue

### ISSUE THREAD

**Issue by mahramane** [pusheco/pushe-android-studio-sample#75]
سلام
پوشه با پروگارد مشکل داره باید حتما کل پکیج رو به پروگارد اضافه کنی که درست شه من از کد زیر استفاده کردم و لی حجم برنامه زیاد شد شما راه حل بهتری ندارید؟ لطفا کمک کنید.
-keep class co.pushe.plus.** { *; }

**Comment by mahdi-malv** [comment]
سلام
میشه بگید هنگام کرش به چه کلاس یا کلاسهایی گیر میده؟

**Comment by mahramane** [comment]
> سلام میشه بگید هنگام کرش به چه کلاس یا کلاسهایی گیر میده؟

به هیچ کلاسی گیر نمیده یا خطایی نمیده ولی پیام هارو دریافت نمیکنه اصلا.
من یه اپلیکیشن منتشر کردم الان 600 کاربر دارم چند روز پیش خواستم پوش ارسال کنم یه دونش هم ارسال نشد برای گوشی خودم هم تست کردم.
بعدا چک کردم دیدم مشکل از پرو گارد بوده چون در حالت دیباگ پیام ها دریافت میشد.

**Comment by mahdi-malv** [comment]
@mahramane 
واقعا معذرت میخوام که با تاخیر جوابتون رو میدم

لطفا این مورد رو تست کنید و ببینید حل میشه؟ من سمت خودم یه تست کیس رو پاس کردم

این مورد توی پروگارد بذارید:

```js
-keepclasseswithmembers class * {
   <init>(...);
    @com.squareup.moshi.* <methods>;
}
```

**Comment by mahdi-malv** [comment]
Preview version `v2.6.4-alpha01` contains this fix. Feel free to try it

**Comment by mahdi-malv** [comment]
Closing. Please re-open if the issue still occurs.
