### ISSUE TITLE
پشتیبانی نشدن از کاتلین

### ISSUE THREAD

**Issue by AmirrezaWeb** [pusheco/pushe-android-studio-sample#78]
سلام من از   aide که یک اپلکیشن واقعی برگرفته از اندروید استادیو است استفاد می کنم  
این اپلکیشن از جاوا پشتیبانی می کند واکامپایلر کاتلین ندارد 
و توسعه آن در 2019 متوقف شده است 
حجم  این اپلکیشن فقط 40 میگابایت است 
خواست کنابخانه به زبان 100% java اضافه کنید 
درصورتی که خواستید با من ... ارتباط داشت باشید
09019451882 or info@amir85.ir

**Comment by mahdi-malv** [comment]
سلام
متاسفانه همچین چیزی ممکن نیست.
با تشکر
