### ISSUE TITLE
Firebase Installations Error

### ISSUE THREAD

**Issue by SudoDios** [pusheco/pushe-android-studio-sample#79]
Hi.
when I am using firebase, it gives error 403 forbidden.  
how to fix ?

**Comment by mahdi-malv** [comment]
Hi
Sounds like related to the FCM itself.
Investigating...

**Comment by SudoDios** [comment]
Thnks

**Comment by mahdi-malv** [comment]
Right now it's solved and Firebase doesn't complain about Iran IP

**Comment by SudoDios** [comment]
Why was that?

**Comment by mahdi-malv** [comment]
Firebase installation was to blame. We talked to one of their leaders and he helped us fix the issue.

**Comment by SudoDios** [comment]
In any case, thanks 🙂
